#spring.profiles.active=test或者pro 来控制加载哪个环境的配置,完整命令如下:
#java -jar xxxxx.jar --spring.profiles.active=test  表示加载测试环境的配置
#java -jar xxxxx.jar --spring.profiles.active=pro  表示加载生产环境的配置

#查看springboot开启了哪些配置
debug: false

## Apollo客户端依赖于AppId https://github.com/ctripcorp/apollo/wiki/Java客户端使用指南
#app:
#  # 需要手动创建，或者直接用apollo默认给出的应用id
#  id: jiiiiiin-server-manager
#apollo:
#  # Apollo Meta Server https://github.com/ctripcorp/apollo/wiki/Java客户端使用指南#122-apollo-meta-server
#  # meta server和config service是部署在同一个JVM进程，所以meta server的地址就是config service的地址。
#  meta: http://localhost:8080
#  # 本地缓存路径
#  # 默认会存储再/opt/data/「appid」
#  # 对应的目录需要有读写权限
#  cacheDir: /Users/jiiiiiin/Documents/IdeaProjects/jiiiiiin-security/apollo-cache-dir
#  # Cluster（集群）
#  cluster: default
#  bootstrap:
#    # 注入默认application namespace的配置示例
#    enabled: true
#    # 把日志相关的配置（如logging.level.root=info或logback-spring.xml中的参数）也放在Apollo管理
#    eagerLoad:
#      enabled: true
#  # Spring Placeholder的使用
#  autoUpdateInjectedSpringProperties: true

#eureka:
#  client:
#    service-url:
#      # 指定服务注册中心的地址
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true

# 通过apollo配置
server:
  port: 8888
eureka:
  client:
    service-url:
      # 指定服务注册中心的地址
      defaultZone: http://jiiiiiin-eureka:8761/eureka/
logging:
  level:
    # 配置日志输出级别以观察SQL的执行情况
    cn:
      jiiiiiin: debug
    com:
      springboot:
        mapper: debug
spring:
  application:
    name: jiiiiiin-auth-center
  oauth2:
    resource:
      # https://my.oschina.net/buwei/blog/910028
      filter-order: 3
  jackson:
    default-property-inclusion: non_null
  redis:
    # 配置redis链接地址
    host: jiiiiiin-redis
    port: 6379
    # Redis数据库索引（默认为0）
    database: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        #        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
      timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jiiiiiin-mysql:3306/vplusdb?&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: vplus
    password: 1qaz@WSX
    # 参考：https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      # 连接池配置
      initial-size: 2
      min-idle: 2
      max-active: 5
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: cn.jiiiiiin.module.*.service.*
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        allow: 127.0.0.1,192.168.1.185
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
  boot:
    admin:
      client:
        url: http://jiiiiiin-springboot-admin:5000
mybatis-plus:
  #Mapper.xml所在的位置
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: cn.jiiiiiin.user.entity
  type-aliases-super-type: cn.jiiiiiin.data.entity.BaseEntity
  # TODO 目前mp+不支持多包配置，故需要把当前模块依赖的枚举都放在一个包下
  type-enums-package: cn.jiiiiiin.user.enums
  global-config:
    db-config:
      id-type: id_worker
    #刷新mapper 调试神器
    refresh: true
    sql-parser-cache: false
  executor-type: reuse
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    #开启MyBatis的二级缓存
    cache-enabled: true

# 自定义配置
jiiiiiin:
  security:
    oauth2:
      tokenStore:
        jwt
        # redis
      clients:
        - clientId: pweb
          clientSecret: pweb

management:
  endpoints:
    web:
      exposure:
        # As with Spring Boot 2 most of the endpoints aren’t exposed via http by default, we expose all of them. For production you should carefully choose which endpoints to expose.
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      # 无效

